# Generated by Django 4.2.7 on 2023-11-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='Default', max_length=80),
            preserve_default=False,
        ),
    ]
