# Generated by Django 4.2.7 on 2023-11-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pessoa_idade_pessoa_email_pessoa_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
    ]
